### ISSUE TITLE
ocnetfs' lfs-server busyloops when nothing's going on.

### ISSUE THREAD

**Issue by AmandaCameron** [OpenPrograms/gamax92-Programs#4]
This can be solved by joining the two selects in update() into one and then passing a non-zero timeout. I'm not sure if my memory is right, but ISTR that the luasocket docs state that passing a negative timeout will make it wait indefinitely, so if there's nothing that needs to be run regularly, it may be most efficent to do that.

**Comment by gamax92** [comment]
Should be fixed by dc07a797843d4044c59fd9f7e0730351dfbc1381
